name: The Orphan Asylum
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49066
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#7c7c7c'
    - '#a4a4a4'
    - '#413830'
  brandStrength: 0.625
  lightness: 0.9715530080720782
  saturation: 0.37532137311063707
  rhythmicContrast: 0.9026898283045739
purpose: []
